### ISSUE TITLE
请问阅读量那个怎么改？那个是html里写死的啊

### ISSUE THREAD

**Issue by kubixiaoguo** [hauk0101/ueditor-preview-html#2]

**Comment by hauk0101** [comment]
你说的是什么阅读量？
阅读量只是一个dom元素，你可以在相关页面里面加上js代码去获取你们服务器的api得到这个值，再显示到对应的页面上就好了。
我在demo里面的阅读量，只是为了做展示用的，并不涉及服务器。

**Comment by kubixiaoguo** [comment]
恩，谢谢回复，阅读量我注掉了，暂时不用那个功能。还有个问题，就是您这个是怎么在手机上适配的啊，我用您的这个demo做完后台管理系统的内容发布模块了，马上要做移动端展示页面了，您能大体说下您的这个编辑器移动端页面接收适配原理吗？

**Comment by kubixiaoguo** [comment]
还发现的小问题就是第一次输入文本，不手动设置字体的时候，查看文本的html发现没有内联font-size，只有手动去设置下字体大小，才能内联上。

**Comment by hauk0101** [comment]
@kubixiaoguo 页面适配你就按照你平时做的就好了啊，还有关于ueditor相关的东西我也没改，我只是提供了一种编辑完成后在PC端能够预览到手机端的效果，主要是为了给运营人员用的，并没有去做真实手机端的适配。

**Comment by kubixiaoguo** [comment]
平常手机端是用rem布局的，也就是这个并没有把内联的那些px样式做转换，并没有解决手机端适配啊 0.0

**Comment by hauk0101** [comment]
@kubixiaoguo  我的意思是我这个demo并不是说你生成出来的就是你最终手机上能用的，这个的目的更多的是为了给运营的人使用的，让他们在后台输入了文章之后，能够点击预览，在PC上模拟一个手机的展示，至于你是不是rem和内联的px我都没做啊，这个你要自己用js或者其他手段再解决。

**Comment by kubixiaoguo** [comment]
恩，明白了，谢谢啊，我以为是解决了移动端的适配问题，那请问您有文本编辑器在h5页面适配的方案吗？例如怎么把px转为rem这样的
